# Generated by Django 5.2.3 on 2025-07-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='worklog_audios/'),
        ),
    ]
