# Generated by Django 5.2.5 on 2025-08-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
        ('worklog', '0003_alter_worklog_options_worklog_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='work_order_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklogs', to='work_order.workorder'),
        ),
    ]
