# Generated by Django 5.2.5 on 2025-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_worklog_work_order_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='status',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_espera_repuestos', 'En Espera de Repuestos'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20),
        ),
    ]
