# Generated by Django 5.2.5 on 2025-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0005_alter_worklog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='field_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='field_km_one_way',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='general_ops_subtype',
            field=models.CharField(blank=True, choices=[('Mandados/tramites', 'Mandados/tramites'), ('Tareas administrativas', 'Tareas administrativas'), ('Movimiento de vehiculos', 'Movimiento de vehiculos'), ('Limpieza', 'Limpieza')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='task_type',
            field=models.CharField(choices=[('Taller', 'Taller'), ('Campo', 'Campo'), ('Diligencia', 'Diligencia'), ('Operaciones generales', 'Operaciones generales'), ('Otros', 'Otros')], max_length=30),
        ),
    ]
