# Generated by Django 5.2.5 on 2025-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_espera_repuestos', 'En Espera de Repuestos'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
    ]
