# Generated by Django 5.2.5 on 2025-08-28 19:41

import work_order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_alter_workorder_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderattachment',
            name='archivo',
            field=models.FileField(upload_to='workorders/', validators=[work_order.validators.validate_workorder_attachment]),
        ),
    ]
