# Generated by Django 5.2.3 on 2025-06-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, unique=True, verbose_name='Razón Social o Nombre del Cliente')),
                ('cuit', models.CharField(help_text='Formato: XX-XXXXXXXX-X (sin guiones)', max_length=13, unique=True, verbose_name='CUIT/CUIL')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
    ]
